---
- name: Install Docker, Azure CLI, and kubectl
  hosts: localhost
  become: yes
  tasks:
    - name: Install Docker dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: Add Docker repository key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg      
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Install pip3
      apt:
        name: python3-pip
        state: present

    - name: Install Azure CLI
      pip:
        name: azure-cli
        state: present

    - name: Add Kubernetes repository key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes repository
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Install kubectl
      apt:
        name: kubectl
        state: present

    - name: Download and install Terraform
      get_url:
        url: "https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip"
        dest: "/tmp/terraform.zip"
      delegate_to: localhost

    - name: Install unzip
      apt:
        name: unzip
        state: present

    - name: Unzip Terraform
      unarchive:
        src: "/tmp/terraform.zip"
        dest: "/usr/local/bin/"
        remote_src: yes
      delegate_to: localhost
